/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view;

import br.com.daosoft.PesquisaSoftDAO;
import br.com.daosoft.VendaSoftDAO;
import br.com.modelsoft.ItensVendaSoft;
import br.com.modelsoft.NfeSoft;
import br.com.modelsoft.TipoPagSoft;
import br.com.modelsoft.VendaSoft;
import br.com.modelsoft.VendasSoft;
import br.com.util.LimitaCaracteres;
import br.com.util.Propries;
import static br.com.util.numformat.adcPorcent;
import java.util.Date;
import static br.com.view.TelaOrcamentoSoft.jtProdutos;
import static br.com.view.TelaOrcamentoSoft.tbTipoPag;
import static br.com.view.TelaOrcamentoSoft.txtCFOPnfe;
import static br.com.view.TelaOrcamentoSoft.txtChaveNfe;
import static br.com.view.TelaOrcamentoSoft.txtCodorc;
import static br.com.view.TelaOrcamentoSoft.txtCpfcnpj;
import static br.com.view.TelaOrcamentoSoft.txtDataNfe;
import static br.com.view.TelaOrcamentoSoft.txtDataorc;
import static br.com.view.TelaOrcamentoSoft.txtDesconto;
import static br.com.view.TelaOrcamentoSoft.txtFrete;
import static br.com.view.TelaOrcamentoSoft.txtIdcliente;
import static br.com.view.TelaOrcamentoSoft.txtLoja;
import static br.com.view.TelaOrcamentoSoft.txtModeloNNfe;
import static br.com.view.TelaOrcamentoSoft.txtNomeCliente;
import static br.com.view.TelaOrcamentoSoft.txtNumeroNfe;
import static br.com.view.TelaOrcamentoSoft.txtObs;
import static br.com.view.TelaOrcamentoSoft.txtProtocoloNfe;
import static br.com.view.TelaOrcamentoSoft.txtSerie;
import static br.com.view.TelaOrcamentoSoft.txtStatus;
import static br.com.view.TelaOrcamentoSoft.txtSubtotal;
import static br.com.view.TelaOrcamentoSoft.txtTotal;
import static br.com.view.TelaOrcamentoSoft.txtValorNfe;
import static br.com.view.TelaOrcamentoSoft.txtVendedor;
import static br.com.view.TelaOrcamentoSoft.txtDescontop;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import static mondrian.olap.fun.vba.Vba.date;
import mondrian.udf.CurrentDateStringUdf;
import static org.joda.time.format.ISODateTimeFormat.date;

/**
 *
 * @author marlon
 */
public class TelaPeqVendaSoft extends javax.swing.JDialog {

    /**
     * Creates new form TelaPesquisaProd
     *
     * @param parent
     * @param modal
     */
    public TelaPeqVendaSoft(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txtNvenda.setDocument(new LimitaCaracteres(10, LimitaCaracteres.TipoEntrada.NUMEROINTEIRO));
        txtCli.setDocument(new LimitaCaracteres(14, LimitaCaracteres.TipoEntrada.NOME));
    }

    private final SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
    private final SimpleDateFormat dt = new SimpleDateFormat("dd.MM.yyyy");

    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");

    NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
    DecimalFormat df = new DecimalFormat("#.##");
    NumberFormat dfp = NumberFormat.getNumberInstance();
    //new DecimalFormat("#.## %");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtVenda = new javax.swing.JTable();
        btnSair = new javax.swing.JToggleButton();
        btnSelecionar = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNvenda = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCli = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbxLoja = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cbxTipoVenda = new javax.swing.JComboBox<>();
        dcDataInicio = new com.toedter.calendar.JDateChooser("dd/MM/yyyy", "##/##/####", '_');
        dcDataInicio.getDateEditor().getUiComponent().addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                ((JTextFieldDateEditor)e.getSource()).selectAll();
            }
        });
        dcDataFim = new com.toedter.calendar.JDateChooser("dd/MM/yyyy", "##/##/####", '_');
        dcDataFim.getDateEditor().getUiComponent().addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                ((JTextFieldDateEditor)e.getSource()).selectAll();
            }
        });
        precoRender1 = new br.com.util.PrecoRender();
        jlRowCount = new javax.swing.JLabel();
        jlTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisa Venda");
        setMinimumSize(new java.awt.Dimension(690, 485));
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jtVenda.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jtVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N Pedido", "Data", "CPF/CNPJ", "Nome Cliente", "Vendedor", "Tipo", "Total Pago"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtVenda.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jtVendaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jtVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtVendaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtVendaMouseEntered(evt);
            }
        });
        jtVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtVendaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtVenda);
        if (jtVenda.getColumnModel().getColumnCount() > 0) {
            jtVenda.getColumnModel().getColumn(0).setMinWidth(70);
            jtVenda.getColumnModel().getColumn(0).setPreferredWidth(70);
            jtVenda.getColumnModel().getColumn(0).setMaxWidth(70);
            jtVenda.getColumnModel().getColumn(1).setMinWidth(130);
            jtVenda.getColumnModel().getColumn(1).setPreferredWidth(130);
            jtVenda.getColumnModel().getColumn(1).setMaxWidth(130);
            jtVenda.getColumnModel().getColumn(2).setMinWidth(110);
            jtVenda.getColumnModel().getColumn(2).setPreferredWidth(110);
            jtVenda.getColumnModel().getColumn(2).setMaxWidth(110);
            jtVenda.getColumnModel().getColumn(4).setMinWidth(90);
            jtVenda.getColumnModel().getColumn(4).setPreferredWidth(90);
            jtVenda.getColumnModel().getColumn(4).setMaxWidth(90);
            jtVenda.getColumnModel().getColumn(5).setMinWidth(110);
            jtVenda.getColumnModel().getColumn(5).setPreferredWidth(110);
            jtVenda.getColumnModel().getColumn(5).setMaxWidth(110);
            jtVenda.getColumnModel().getColumn(6).setMinWidth(90);
            jtVenda.getColumnModel().getColumn(6).setPreferredWidth(90);
            jtVenda.getColumnModel().getColumn(6).setMaxWidth(90);
            jtVenda.getColumnModel().getColumn(6).setCellRenderer(precoRender1);
        }

        btnSair.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/img/icons8-desligar-18.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnSelecionar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/img/icons8-ok-18.png"))); // NOI18N
        btnSelecionar.setText("Selecionar");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setText("Data Início:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel2.setText("Data Fim:");

        txtNvenda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel3.setText("N Venda:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel5.setText("CPF/CNPJ:");

        txtCli.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel6.setText("Loja:");

        cbxLoja.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cbxLoja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2 - CEILANDIA" }));
        cbxLoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLojaActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/img/icons8-pesquisar-18.png"))); // NOI18N
        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/img/icons8-pesquisar-18.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel7.setText("Tipo:");

        cbxTipoVenda.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cbxTipoVenda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "T - TODOS", "O - ORÇAMENTO", "V - VENDA" }));
        cbxTipoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoVendaActionPerformed(evt);
            }
        });

        dcDataInicio.setToolTipText("");
        dcDataInicio.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        dcDataFim.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dcDataInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dcDataFim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNvenda, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCli, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxLoja, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxTipoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(82, 82, 82)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(txtCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(cbxLoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(cbxTipoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtNvenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addComponent(dcDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dcDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jlRowCount.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jlTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(precoRender1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlRowCount, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(633, 633, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jlTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(19, 19, 19))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSair)
                                .addGap(34, 34, 34)
                                .addComponent(btnSelecionar))))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlRowCount, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelecionar)
                    .addComponent(btnSair)
                    .addComponent(precoRender1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtVendaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jtVendaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jtVendaAncestorAdded

    private void jtVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtVendaMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            try {
                setar();
                readProd();
                readTipo();
                setarNfe();
            } catch (IOException ex) {
                Logger.getLogger(TelaPeqVendaSoft.class.getName()).log(Level.SEVERE, null, ex);
            }

            dispose();
        }

    }//GEN-LAST:event_jtVendaMouseClicked

    private void jtVendaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtVendaMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jtVendaMouseEntered

    private void jtVendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtVendaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                setar();
                readProd();
                readTipo();
                setarNfe();
                dispose();
            } catch (IOException ex) {
                Logger.getLogger(TelaPeqVendaSoft.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jtVendaKeyPressed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        TelaOrcamentoSoft.conVendaSoft = false;

        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        try {
            // TODO add your handling code here:
            setar();
            readProd();
            readTipo();
            setarNfe();
            dispose();
        } catch (IOException ex) {
            Logger.getLogger(TelaPeqVendaSoft.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            readVenda();
            totalTable();

        } catch (IOException ex) {
            Logger.getLogger(TelaPeqVendaSoft.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        TelaPesqCliSoft objConCli = new TelaPesqCliSoft(null, true);

        objConCli.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            // TODO add your handling code here:

            opemTelaVenda();

        } catch (IOException | ParseException ex) {
            Logger.getLogger(TelaPeqVendaSoft.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            // TODO add your handling code here:
            File file = new File("./src/properties/querysoft.properties");

            if (file.exists()) {

                readVenda();

            }

        } catch (IOException ex) {
            Logger.getLogger(TelaPeqVendaSoft.class.getName()).log(Level.SEVERE, null, ex);
        }

        totalTable();

    }//GEN-LAST:event_formWindowOpened

    private void cbxTipoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoVendaActionPerformed

    private void cbxLojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLojaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxLojaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPeqVendaSoft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPeqVendaSoft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPeqVendaSoft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPeqVendaSoft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaPeqVendaSoft dialog = new TelaPeqVendaSoft(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnSair;
    private javax.swing.JToggleButton btnSelecionar;
    private javax.swing.JComboBox<String> cbxLoja;
    private javax.swing.JComboBox<String> cbxTipoVenda;
    private com.toedter.calendar.JDateChooser dcDataFim;
    private com.toedter.calendar.JDateChooser dcDataInicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlRowCount;
    private javax.swing.JLabel jlTotal;
    public static javax.swing.JTable jtVenda;
    private br.com.util.PrecoRender precoRender1;
    public static javax.swing.JTextField txtCli;
    public static javax.swing.JTextField txtNvenda;
    // End of variables declaration//GEN-END:variables

    public void readVenda() throws IOException {
        String DtInicio = null;
        String DtFim = null;

        if (dcDataInicio.getDate() != null) {
            DtInicio = dt.format(dcDataInicio.getDate());
        }

        if (dcDataFim.getDate() != null) {
            DtFim = dt.format(dcDataFim.getDate());
        }

        String parametro = "cast(o.datastatus as date) between " + "'" + DtInicio + "'" + " and " + "'" + DtFim + "'";

        switch (cbxTipoVenda.getSelectedIndex()) {
            case 0:
                if (txtNvenda.getText().isEmpty()) {

                    if (cbxLoja.getSelectedItem() == "1 - SAMABAIA" && txtCli.getText().isEmpty()) {
                        parametro = "o.data between " + "'" + DtInicio + "'" + " and " + "'" + DtFim + "'" + " and o.loja = 1";
                    }
                    if (cbxLoja.getSelectedItem() == "2 - CEILANDIA" && txtCli.getText().isEmpty()) {
                        parametro = "o.data between " + "'" + DtInicio + "'" + " and " + "'" + DtFim + "'" + " and o.loja = 2";
                    }
                    if (cbxLoja.getSelectedItem() == "1 - SAMABAIA" && !txtCli.getText().isEmpty()) {
                        parametro = "o.data between " + "'" + DtInicio + "'" + " and " + "'" + DtFim + "'" + " and o.loja = 1 and o.cgc = '" + txtCli.getText() + "'";
                    }
                    if (cbxLoja.getSelectedItem() == "2 - CEILANDIA" && !txtCli.getText().isEmpty()) {
                        parametro = "o.data between " + "'" + DtInicio + "'" + " and " + "'" + DtFim + "'" + " and o.loja = 2 and o.cgc = '" + txtCli.getText() + "'";
                    }
                } else {
                    if (cbxLoja.getSelectedItem() == "1 - SAMABAIA" && txtCli.getText().isEmpty()) {
                        parametro = "o.data between " + "'" + DtInicio + "'" + " and " + "'" + DtFim + "'" + " and o.loja = 1 and o.codorcamento = " + txtNvenda.getText();
                    }
                    if (cbxLoja.getSelectedItem() == "2 - CEILANDIA" && txtCli.getText().isEmpty()) {
                        parametro = "o.data between " + "'" + DtInicio + "'" + " and " + "'" + DtFim + "'" + " and o.loja = 2 and o.codorcamento = " + txtNvenda.getText();
                    }
                    if (cbxLoja.getSelectedItem() == "1 - SAMABAIA" && !txtCli.getText().isEmpty()) {
                        parametro = "o.data between " + "'" + DtInicio + "'" + " and " + "'" + DtFim + "'" + " and o.loja = 1 and o.cgc = '" + txtCli.getText() + "' and o.codorcamento = " + txtNvenda.getText();
                    }
                    if (cbxLoja.getSelectedItem() == "2 - CEILANDIA" && !txtCli.getText().isEmpty()) {
                        parametro = "o.data between " + "'" + DtInicio + "'" + " and " + "'" + DtFim + "'" + " and o.loja = 2 and o.cgc = '" + txtCli.getText() + "' and o.codorcamento = " + txtNvenda.getText();

                    }
                }
                break;
            case 1:
                if (txtNvenda.getText().isEmpty()) {

                    if (cbxLoja.getSelectedItem() == "1 - SAMABAIA" && txtCli.getText().isEmpty()) {
                        parametro = "o.data between " + "'" + DtInicio + "'" + " and " + "'" + DtFim + "'" + " and o.loja = 1" + " and o.status in (0,4,5)";
                    }
                    if (cbxLoja.getSelectedItem() == "2 - CEILANDIA" && txtCli.getText().isEmpty()) {
                        parametro = "o.data between " + "'" + DtInicio + "'" + " and " + "'" + DtFim + "'" + " and o.loja = 2" + " and o.status in (0,4,5)";
                    }
                    if (cbxLoja.getSelectedItem() == "1 - SAMABAIA" && !txtCli.getText().isEmpty()) {
                        parametro = "o.data between " + "'" + DtInicio + "'" + " and " + "'" + DtFim + "'" + " and o.loja = 1 and o.cgc = '" + txtCli.getText() + "' and o.status in (0,4,5)";
                    }
                    if (cbxLoja.getSelectedItem() == "2 - CEILANDIA" && !txtCli.getText().isEmpty()) {
                        parametro = "o.data between " + "'" + DtInicio + "'" + " and " + "'" + DtFim + "'" + " and o.loja = 2 and o.cgc = '" + txtCli.getText() + "' and o.status in (0,4,5)";
                    }
                } else {
                    if (cbxLoja.getSelectedItem() == "1 - SAMABAIA" && txtCli.getText().isEmpty()) {
                        parametro = "o.data between " + "'" + DtInicio + "'" + " and " + "'" + DtFim + "'" + " and o.loja = 1 and o.codorcamento = " + txtNvenda.getText() + " and o.status in (0,4,5)";
                    }
                    if (cbxLoja.getSelectedItem() == "2 - CEILANDIA" && txtCli.getText().isEmpty()) {
                        parametro = "o.data between " + "'" + DtInicio + "'" + " and " + "'" + DtFim + "'" + " and o.loja = 2 and o.codorcamento = " + txtNvenda.getText() + " and o.status in (0,4,5)";
                    }
                    if (cbxLoja.getSelectedItem() == "1 - SAMABAIA" && !txtCli.getText().isEmpty()) {
                        parametro = "o.data between " + "'" + DtInicio + "'" + " and " + "'" + DtFim + "'" + " and o.loja = 1 and o.cgc = '" + txtCli.getText() + "' and o.codorcamento = " + txtNvenda.getText() + " and o.status in (0,4,5)";
                    }
                    if (cbxLoja.getSelectedItem() == "2 - CEILANDIA" && !txtCli.getText().isEmpty()) {
                        parametro = "o.data between " + "'" + DtInicio + "'" + " and " + "'" + DtFim + "'" + " and o.loja = 2 and o.cgc = '" + txtCli.getText() + "' and o.codorcamento = " + txtNvenda.getText() + " and o.status in (0,4,5)";

                    }
                }
                break;
            case 2:
                if (txtNvenda.getText().isEmpty()) {

                    if (cbxLoja.getSelectedItem() == "1 - SAMABAIA" && txtCli.getText().isEmpty()) {
                        parametro = "o.data between " + "'" + DtInicio + "'" + " and " + "'" + DtFim + "'" + " and o.loja = 1" + " and o.status in (1)";
                    }
                    if (cbxLoja.getSelectedItem() == "2 - CEILANDIA" && txtCli.getText().isEmpty()) {
                        parametro = "o.data between " + "'" + DtInicio + "'" + " and " + "'" + DtFim + "'" + " and o.loja = 2" + " and o.status in (1)";
                    }
                    if (cbxLoja.getSelectedItem() == "1 - SAMABAIA" && !txtCli.getText().isEmpty()) {
                        parametro = "o.data between " + "'" + DtInicio + "'" + " and " + "'" + DtFim + "'" + " and o.loja = 1 and o.cgc = '" + txtCli.getText() + "' and o.status in (1)";
                    }
                    if (cbxLoja.getSelectedItem() == "2 - CEILANDIA" && !txtCli.getText().isEmpty()) {
                        parametro = "o.data between " + "'" + DtInicio + "'" + " and " + "'" + DtFim + "'" + " and o.loja = 2 and o.cgc = '" + txtCli.getText() + "' and o.status in (1)";
                    }
                } else {
                    if (cbxLoja.getSelectedItem() == "1 - SAMABAIA" && txtCli.getText().isEmpty()) {
                        parametro = "o.data between " + "'" + DtInicio + "'" + " and " + "'" + DtFim + "'" + " and o.loja = 1 and o.codorcamento = " + txtNvenda.getText() + " and o.status in (1)";
                    }
                    if (cbxLoja.getSelectedItem() == "2 - CEILANDIA" && txtCli.getText().isEmpty()) {
                        parametro = "o.data between " + "'" + DtInicio + "'" + " and " + "'" + DtFim + "'" + " and o.loja = 2 and o.codorcamento = " + txtNvenda.getText() + " and o.status in (1)";
                    }
                    if (cbxLoja.getSelectedItem() == "1 - SAMABAIA" && !txtCli.getText().isEmpty()) {
                        parametro = "o.data between " + "'" + DtInicio + "'" + " and " + "'" + DtFim + "'" + " and o.loja = 1 and o.cgc = '" + txtCli.getText() + "' and o.codorcamento = " + txtNvenda.getText() + " and o.status in (1)";
                    }
                    if (cbxLoja.getSelectedItem() == "2 - CEILANDIA" && !txtCli.getText().isEmpty()) {
                        parametro = "o.data between " + "'" + DtInicio + "'" + " and " + "'" + DtFim + "'" + " and o.loja = 2 and o.cgc = '" + txtCli.getText() + "' and o.codorcamento = " + txtNvenda.getText() + " and o.status in (1)";

                    }
                }
                break;
            default:
                break;
        }

        DefaultTableModel modelo = (DefaultTableModel) jtVenda.getModel();
        modelo.setNumRows(0);
        PesquisaSoftDAO dao = new PesquisaSoftDAO();

        Propries set = new Propries();

        File file = new File("./src/properties/querysoft.properties");

        if (!file.exists()) {

            file.createNewFile();
            OutputStream output = new FileOutputStream(file);
            output.close();

        }

        set.setar("data.inicio", DtInicio, file);
        set.setar("data.fim", DtFim, file);
        set.setar("cod.cliente", txtCli.getText(), file);
        set.setar("nun.venda", txtNvenda.getText(), file);
        set.setar("num.loja", (String) cbxLoja.getSelectedItem(), file);
        set.setar("tipo.venda", (String) cbxTipoVenda.getSelectedItem(), file);

        System.out.println("PARAMETROS readVenda() " + parametro);

        dao.conVendas(parametro).forEach((VendasSoft v) -> {
            modelo.addRow(new Object[]{
                v.getCondigo(),
                sdf.format(v.getData()),
                v.getCgc(),
                v.getNome(),
                v.getVendedor(),
                v.getStatus(),
                v.getTotal()

            });
        });

    }

    public void opemTelaVenda() throws IOException, ParseException {

        File file = new File("./src/properties/querysoft.properties");

        if (file.exists()) {

            Propries get = new Propries();

            dcDataInicio.setDate(dt.parse(get.getProp("data.inicio", file)));
            dcDataFim.setDate(dt.parse(get.getProp("data.fim", file)));
            txtCli.setText(get.getProp("cod.cliente", file));
            txtNvenda.setText(get.getProp("nun.venda", file));
            cbxLoja.setSelectedItem(get.getProp("num.loja", file));
            cbxTipoVenda.setSelectedItem(get.getProp("tipo.venda", file));
        } else {

            file.createNewFile();
            OutputStream output = new FileOutputStream(file);
            output.close();

        }

    }

    private void setar() throws IOException {

        VendaSoftDAO dao = new VendaSoftDAO();

        VendaSoft v = new VendaSoft();

        dao.readvendas(v);

        txtCodorc.setText(String.valueOf(v.getCondigo()));
        txtDataorc.setText(sdf.format(v.getData()));
        txtIdcliente.setText(v.getCodcli().toString());
        txtCpfcnpj.setText(v.getCgc());
        txtNomeCliente.setText(v.getNome());
        txtVendedor.setText(v.getVendedor());
        txtStatus.setText(v.getStatus());
        txtSubtotal.setText(nf.format(v.getSubtotal()));
        txtDesconto.setText(nf.format(v.getDescontor()));
        txtDescontop.setText(adcPorcent(v.getDescontop()));
        txtFrete.setText(nf.format(v.getFrete()));
        txtTotal.setText(nf.format(v.getTotal()));
        txtLoja.setText(v.getLoja().toString());
        /*if (v.getTipopag() == null) {
        } else {
            TxtTipoPag.setText(v.getTipopag().toUpperCase());
        }*/

    }

    private void setarNfe() throws IOException {

        VendaSoftDAO dao = new VendaSoftDAO();

        NfeSoft n = new NfeSoft();

        dao.readNfe(n);

        if (n.getNumero() != null) {
            txtDataNfe.setText(sdf.format(n.getData()));

            txtValorNfe.setText(nf.format(n.getValor()));
            txtCFOPnfe.setText(n.getCfop());
            txtNumeroNfe.setText(String.valueOf(n.getNumero()));
            txtSerie.setText(String.valueOf(n.getSerie()));
            txtModeloNNfe.setText(n.getModelo());
            txtChaveNfe.setText(n.getChave());
            txtProtocoloNfe.setText(n.getProtocolo());
            txtObs.setText(n.getObs());
        } else {
            txtDataNfe.setText("");

            txtValorNfe.setText("");
            txtCFOPnfe.setText("");
            txtNumeroNfe.setText("");
            txtSerie.setText("");
            txtModeloNNfe.setText("");
            txtChaveNfe.setText("");
            txtProtocoloNfe.setText("");
            txtObs.setText("");
        }

        //txtDataorc.setText(sdf.format(v.getData()));
    }

    public void readProd() throws IOException {

        DefaultTableModel modelo = (DefaultTableModel) jtProdutos.getModel();
        modelo.setNumRows(0);
        VendaSoftDAO vdao = new VendaSoftDAO();

        vdao.readProd().forEach((ItensVendaSoft i) -> {
            modelo.addRow(new Object[]{
                i.getItem(),
                i.getCodigo(),
                i.getCodBarras(),
                i.getDescricao(),
                i.getCodembalagem(),
                i.getQuantidade(),
                i.getValorund(),
                i.getValortotal()

            });
        });

    }

    public void readTipo() throws IOException {
        DefaultTableModel modelo = (DefaultTableModel) tbTipoPag.getModel();
        modelo.setNumRows(0);
        VendaSoftDAO vdao = new VendaSoftDAO();

        vdao.readTipo().forEach((TipoPagSoft t) -> {
            modelo.addRow(new Object[]{
                t.getCodigo(),
                t.getDescricao(),
                t.getValor()

            });
        });

    }

    public void totalTable() {

        int numrow = jtVenda.getRowCount();

        double total = 0;

        for (int i = 0; i < numrow; i++) {

            double valor = Double.parseDouble(jtVenda.getValueAt(i, 6).toString());
            total += valor;

        }

        jlTotal.setText("Total:   " + nf.format(total));

        jlRowCount.setText(String.valueOf(numrow) + " Registros");

    }

}
