/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view;


import br.com.daosoft.ClienteSoftDAO;
import br.com.modelsoft.ClienteSoft;
import static br.com.view.TelaPeqVendaSoft.txtCli;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marlon
 */
public class TelaPesqCliSoft extends javax.swing.JDialog {

    /**
     * Creates new form TelaPesquisaProd
     *
     * @param parent
     * @param modal
     */
    public TelaPesqCliSoft(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public static boolean telaPesquisaProd;
    private final SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        precoRender1 = new br.com.util.PrecoRender();
        cbxPesq = new javax.swing.JComboBox<>();
        txtPesquisaCli = new javax.swing.JTextField();
        btnPesqCli = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCli = new javax.swing.JTable();
        btnSair = new javax.swing.JToggleButton();
        btnSelecionar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisa de Clientes");
        setMinimumSize(new java.awt.Dimension(690, 485));
        setModal(true);
        setResizable(false);

        cbxPesq.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cbxPesq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOME", "CGC", "CODIGO" }));

        txtPesquisaCli.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtPesquisaCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisaCliKeyPressed(evt);
            }
        });

        btnPesqCli.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnPesqCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/img/icons8-pesquisar-18.png"))); // NOI18N
        btnPesqCli.setText("Pesquisar");
        btnPesqCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqCliActionPerformed(evt);
            }
        });

        jTableCli.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jTableCli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Condigo", "CGC", "Nome", "Celular", "Cidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCli.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTableCliAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTableCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCliMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTableCliMouseEntered(evt);
            }
        });
        jTableCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableCliKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCli);
        if (jTableCli.getColumnModel().getColumnCount() > 0) {
            jTableCli.getColumnModel().getColumn(0).setMinWidth(80);
            jTableCli.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTableCli.getColumnModel().getColumn(0).setMaxWidth(80);
            jTableCli.getColumnModel().getColumn(1).setMinWidth(130);
            jTableCli.getColumnModel().getColumn(1).setPreferredWidth(130);
            jTableCli.getColumnModel().getColumn(1).setMaxWidth(130);
            jTableCli.getColumnModel().getColumn(3).setMinWidth(110);
            jTableCli.getColumnModel().getColumn(3).setPreferredWidth(110);
            jTableCli.getColumnModel().getColumn(3).setMaxWidth(110);
            jTableCli.getColumnModel().getColumn(4).setMinWidth(150);
            jTableCli.getColumnModel().getColumn(4).setPreferredWidth(150);
            jTableCli.getColumnModel().getColumn(4).setMaxWidth(150);
        }

        btnSair.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/img/icons8-cancelar-2-18.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnSelecionar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/img/icons8-ok-18.png"))); // NOI18N
        btnSelecionar.setText("Selecionar");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(precoRender1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(774, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnSair)
                            .addGap(18, 18, 18)
                            .addComponent(btnSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cbxPesq, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(txtPesquisaCli, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(btnPesqCli)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(412, Short.MAX_VALUE)
                .addComponent(precoRender1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxPesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPesquisaCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPesqCli))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSelecionar)
                        .addComponent(btnSair))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisaCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaCliKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                readCli();
            } catch (IOException ex) {
                Logger.getLogger(TelaPesqCliSoft.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_txtPesquisaCliKeyPressed

    private void btnPesqCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqCliActionPerformed
        try {
            // TODO add your handling code here:
            readCli();
        } catch (IOException ex) {
            Logger.getLogger(TelaPesqCliSoft.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnPesqCliActionPerformed

    private void jTableCliAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTableCliAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableCliAncestorAdded

    private void jTableCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCliMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            setar();
            dispose();

        }

    }//GEN-LAST:event_jTableCliMouseClicked

    private void jTableCliMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCliMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jTableCliMouseEntered

    private void jTableCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableCliKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            setar();
            //conCli = false;
            dispose();
            //ativarcampos();

        }
    }//GEN-LAST:event_jTableCliKeyPressed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:

        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        // TODO add your handling code here:
        setar();
        //conCli = false;
        dispose();
        // ativarcampos();
    }//GEN-LAST:event_btnSelecionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPesqCliSoft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPesqCliSoft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPesqCliSoft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPesqCliSoft.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaPesqCliSoft dialog = new TelaPesqCliSoft(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesqCli;
    private javax.swing.JToggleButton btnSair;
    private javax.swing.JToggleButton btnSelecionar;
    private javax.swing.JComboBox<String> cbxPesq;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTableCli;
    private br.com.util.PrecoRender precoRender1;
    public static javax.swing.JTextField txtPesquisaCli;
    // End of variables declaration//GEN-END:variables

    public void readCli() throws IOException {

        String condicao = "order by 1";

        if (cbxPesq.getSelectedItem() == "CGC" && !txtPesquisaCli.getText().isEmpty()) {
            condicao = " where c.cgc = '" + txtPesquisaCli.getText() + "'";
        }
        if (cbxPesq.getSelectedItem() == "NOME" && !txtPesquisaCli.getText().isEmpty()) {

            condicao = " where c.razaosocial containing '" + txtPesquisaCli.getText() + "'";

        }

        if (cbxPesq.getSelectedItem() == "CODIGO" && !txtPesquisaCli.getText().isEmpty()) {
            condicao = " where c.codigo = " + txtPesquisaCli.getText();
        }

        DefaultTableModel modelo = (DefaultTableModel) jTableCli.getModel();
        modelo.setNumRows(0);
        ClienteSoftDAO dao = new ClienteSoftDAO();

        dao.conClientes(condicao).forEach((ClienteSoft c) -> {
            modelo.addRow(new Object[]{
                c.getCodigo(),
                c.getCgc(),
                c.getNome(),
                c.getFone(),
                c.getCidade()

            });
        });

    }

    private void setar() {

        int setar = jTableCli.getSelectedRow();
        String idcli = jTableCli.getValueAt(jTableCli.getSelectedRow(), 1).toString();

        txtCli.setText(idcli);

    }

}
